[project]
name = "typehints_pg"
version = "0.0.1"
description = "typehints_pg"
readme = "README.md"
license = "MIT"
authors = [{ name = "Luiz Otávio" }]
requires-python = ">=3.13"
dependencies = [
  "ffmpeg-python>=0.2.0",
  "imagehash>=4.3.2",
  "numpy>=2.3.2",
  "opencv-python>=4.11.0.86",
  "pillow>=11.3.0",
  "pyautogui>=0.9.54",
  "rich>=14.1.0",
  "typing-extensions>=4.14.1",
]

[project.urls]
Homepage = "https://github.com/luizomf/typehints_python_playground"
Documentation = "https://github.com/luizomf/typehints_python_playground"
Repository = "https://github.com/luizomf/typehints_python_playground.git"
Issues = "https://github.com/luizomf/typehints_python_playground/issues"

[project.optional-dependencies]
dev = ["ruff", "pyright", "pytest", "pytest-xdist"]

[project.scripts]
typehints_pg = "main:run"

[tool.ruff]
line-length = 88
target-version = "py313"
fix = true
show-fixes = true
indent-width = 4
exclude = ["venv", ".venv", "env", ".env", "node_modules", "__pycache__"]

[tool.ruff.lint]
select = ["ALL"]
preview = true
ignore = [
  'D',
  'CPY001',
  'T201',
  'FURB118',
  'UP028',
  'ERA001',
  'FBT001',
  'FBT002',
  'FBT003',
  'S101',
  'DOC201',
  'DTZ',
  'RUF003',
]
fixable = ["ALL"]
unfixable = ['D']
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN201", "S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
known-first-party = ["typehints_pg"]

[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.13"
ignore = []
include = ['.']
exclude = ["**/.venv"]
venv = ".venv"
venvPath = "."
executionEnvironments = [{ root = "." }]

[tool.pytest.ini_options]
addopts = "-s --color=yes --tb=short"
pythonpath = ["."]
testpaths = ["tests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]

package-dir = { "" = "." }
